# Global platform settings
# platform :ios, '9.0'

target 'MFFStarterIOSSwift' do
  use_frameworks!
  platform :ios, 9.0

  pod 'IBMMobileFirstPlatformFoundation', '8.0.2018040422'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
